FROM nginx:1.24.0
LABEL maintainer='Image Maintainers <hanxiao2100@qq.com>'

COPY pkg/DNS_nginx_proxy/etc/nginx/ /etc/nginx/
COPY pkg/DNS_nginx_proxy/docker-entrypoint.sh /

RUN set -eux; \
    mkdir -p /origin/nginx/etc; \
    cp -a /etc/nginx /origin/nginx/etc/; \
    # docker-entrypoint.sh; \
    chmod +x /docker-entrypoint.sh;

VOLUME ["/etc/nginx", "/var/log/nginx"]

ENTRYPOINT ["/docker-entrypoint.sh"]
EXPOSE 53/udp 53/tcp
STOPSIGNAL SIGQUIT
CMD ["nginx", "-g", "daemon off;"]