# builder_bind
FROM rockylinux:9.3 AS builder_bind
ADD pkg/BIND/bind-9.16.39.tar.xz /usr/local/src/
COPY pkg/linux/CentOS-Stream9-CRB.repo /etc/yum.repos.d/
COPY pkg/linux/RPM-GPG-KEY-centosofficial /etc/pki/rpm-gpg/

RUN set -eux; \
    dnf -y install epel-release epel-next-release --skip-broke; \
    dnf config-manager --set-enabled crb; \
    dnf clean all; \
    dnf makecache; \
    # 关联动态库; \
    echo -e "/usr/local/lib\n\
/usr/local/lib64\n\
/lib\n\
/lib64\n\
/usr/lib\n\
/usr/lib64\n\
" >> /etc/ld.so.conf; \
    ldconfig; \
    # postgresql yum 库; \
    dnf install -y https://download.postgresql.org/pub/repos/yum/reporpms/EL-9-x86_64/pgdg-redhat-repo-latest.noarch.rpm; \
    #dnf -qy module disable postgresql; \
    # 安装最新版本PostgreSQL; \
    dnf -y install postgresql15 postgresql15-libs libpq5 libpq5-devel; \
    dnf -y install gcc automake autoconf libtool make gcc gcc-c++ wget ; \
    dnf -y install python3-ply perl-diagnostics epel-release diffutils; \
    dnf -y install libuv libuv-devel libnghttp2-devel libcap libcap-devel jemalloc jemalloc-devel --nobest --skip-broken; \
    cd /usr/local/src/bind-9.16.39; \
    #wget https://downloads.isc.org/isc/bind9/9.16.39/bind-9.16.39.tar.xz; \
    #tar -Jxvf bind-9.16.39.tar.xz; \
    #cd bind-9.16.39; \
    export LDFLAGS=-L/usr/pgsql-15/lib; \
    ./configure --prefix=/usr/local/bind_9.16.39 --with-dlz-postgres=yes --enable-epoll --enable-largefile; \
    make; \
    make install;

# origin
FROM rockylinux:9.3
LABEL maintainer='Image Maintainers <hanxiao2100@qq.com>'

ARG BIND_PATH=/usr/local/bind_9.16.39

COPY pkg/linux/CentOS-Stream9-CRB.repo /etc/yum.repos.d/
COPY pkg/linux/RPM-GPG-KEY-centosofficial /etc/pki/rpm-gpg/
COPY pkg/BIND/docker-entrypoint2.sh /
COPY pkg/BIND/config/dlz-postgres/etc/named/ ${BIND_PATH}/etc/
COPY pkg/BIND/docker_init_info.sh ${BIND_PATH}/etc/
COPY --from=builder_bind /usr/local/bind_9.16.39 /usr/local/bind_9.16.39/

RUN set -eux; \
    dnf -y install epel-release epel-next-release --skip-broke; \
    dnf config-manager --set-enabled crb; \
    dnf clean all; \
    dnf makecache; \
    # 关联动态库; \
    echo -e "/usr/local/lib\n\
/usr/local/lib64\n\
/lib\n\
/lib64\n\
/usr/lib\n\
/usr/lib64\n\
" >> /etc/ld.so.conf; \
    ldconfig; \
    # postgresql yum 库; \
    dnf install -y https://download.postgresql.org/pub/repos/yum/reporpms/EL-9-x86_64/pgdg-redhat-repo-latest.noarch.rpm; \
    #dnf -qy module disable postgresql; \
    # 安装最新版本PostgreSQL; \
    dnf -y install postgresql15 postgresql15-libs libpq5 libpq5-devel; \
    # Install BIND; \
    dnf -y install libuv libuv-devel procps-ng --nobest --skip-broken; \
    ln -s /usr/local/bind_9.16.39 /usr/local/bind; \
    ln -s /usr/local/bind/bin/nslookup /usr/bin/; \
    ln -s /usr/local/bind/bin/dig /usr/bin/; \
    groupadd -g 25 named; \
    useradd named -M -u 25 -g 25 -s /sbin/nologin; \
    mkdir -p /usr/local/bind/var; chown -R named:named /usr/local/bind/var; \
    mkdir -p /var/log/named /usr/local/bind/etc/conf.d; chown -R named.named /var/log/named; \
    mkdir -p /dns/origin/bind; \
    cp -a /usr/local/bind/etc /dns/origin/bind/; \
    mv /usr/local/bind/etc /etc/named; \
    ln -s /etc/named /usr/local/bind/etc; \
    # docker-entrypoint2.sh; \
    chmod +x /docker-entrypoint2.sh; \
    # Clear work; \
    rm -rf /usr/local/src/*; \
    dnf clean all;
    
VOLUME ["/etc/named", "/var/log/named"]
EXPOSE 53/udp 53/tcp 953/tcp

ENTRYPOINT ["/docker-entrypoint2.sh"]