FROM cucker/python:python_docker_1.0
LABEL maintainer='Image Maintainers <hanxiao2100@qq.com>'

COPY resolve_container_run_parameters.py /

ENTRYPOINT [ "python", "/resolve_container_run_parameters.py" ]
CMD [ "--help" ]
